import type { Metadata } from "next";
import "./globals.css";
import { url } from "inspector";

export const metadata: Metadata = {
  title: "Last MTA Game | Comming Soon...",
  description: "Generated by next app, dev by Mostafa Kahani",
  authors: [
    { url: "https://github.com/Mostafakahani", name: "Mostafa kahani" },
  ],
  keywords:
    "MTA,mta,ام تی ای, لست ام تی ای, بازی, بازی ویندوز, بازی لست ام تی ای, mta game, last, lastmta,gtasa, gtasanandres,gta:sa, rockstar,rock star",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
